import React from "react";
import type { Metadata } from "next";
import { LayoutProps } from "@/types/layout";
import { getServerSession } from "@/utils/session";
import SessionProvider from "@/components/session-provider";
import ThemeProvider from "@/components/theme-provider";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children }: LayoutProps) {
  const session = await getServerSession();

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="h-full min-h-screen w-full overflow-x-hidden font-family-sans text-base font-normal not-italic leading-normal antialiased">
        <ThemeProvider enableSystem defaultTheme="system" attribute="class">
          <SessionProvider session={session}>{children}</SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
